In [1]:
import tensorflow as tf

In [2]:
identity=tf.eye(num_rows=5,num_columns=None,batch_shape=None,dtype=tf.dtypes.float32,name=None)
print(identity)

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
