<a href="https://colab.research.google.com/github/Joydeep2005Banik/deep_learning_journey/blob/main/math_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf

In [9]:
x_abs=tf.constant([-2.5,3.25])
tf.abs(x_abs)
tf.abs(tf.constant(-0.2))
x_abs_complex=tf.constant([-2.45+4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.34462347])>

In [10]:
tf.sqrt((-2.5)**2 + 4.75*2)

<tf.Tensor: shape=(), dtype=float32, numpy=3.9686269760131836>

In [11]:
x1=tf.constant([5,3,6,6,4,6],dtype=tf.int32)
x2=tf.constant([7,6,2,6,7,11],dtype=tf.int32)
print(tf.add(x1,x2))
print(tf.multiply(x1,x2))
print(tf.divide(x1,x2))
print(tf.subtract(x1,x2))

tf.Tensor([12  9  8 12 11 17], shape=(6,), dtype=int32)
tf.Tensor([35 18 12 36 28 66], shape=(6,), dtype=int32)
tf.Tensor([0.71428571 0.5        3.         1.         0.57142857 0.54545455], shape=(6,), dtype=float64)
tf.Tensor([-2 -3  4  0 -3 -5], shape=(6,), dtype=int32)


In [12]:
x3=tf.constant([5,3,6,6,4,6],dtype=tf.float32)
x4=tf.constant([7,6,2,6,0,11],dtype=tf.float32)
print(tf.math.divide_no_nan(x3,4))

tf.Tensor([1.25 0.75 1.5  1.5  1.   1.5 ], shape=(6,), dtype=float32)


In [13]:
x5=tf.constant([5,3,6,6,4,6],dtype=tf.float32)
x6=tf.constant([7],dtype=tf.float32)
print(tf.math.add(x5,x6))

tf.Tensor([12. 10. 13. 13. 11. 13.], shape=(6,), dtype=float32)


In [14]:
y1=tf.constant([5,3,6,6,4,6],dtype=tf.float32)
y2=tf.constant([[7],[5],[3]],dtype=tf.float32)
print(y1.shape)
print(y2.shape)
print(tf.math.multiply(y1,y1))

(6,)
(3, 1)
tf.Tensor([25.  9. 36. 36. 16. 36.], shape=(6,), dtype=float32)


In [15]:
z=tf.constant([200,120,130,300,60])
print(tf.math.argmax(z))
print(tf.math.argmin(z))

tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)


In [16]:
j=tf.constant([[2,20,30,3,6],
              [3,11,16,1,8],
              [14,45,23,5,27]])
print(tf.math.argmax(j,0))
print(tf.math.argmax(j,1))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [17]:
a=tf.constant([[2,2],[3,3]])
b=tf.constant([[3,1],[1,4]])
tf.pow(a,b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  2],
       [ 3, 81]], dtype=int32)>

In [18]:
d=tf.constant([[1,2,0],
               [3,5,-1],
               [1,5,6],
               [2,3,8]])
print(tf.math.reduce_sum(d,axis=None,keepdims=False,name=None))
print(tf.math.reduce_sum(d,axis=0,keepdims=False,name=None))
print(tf.math.reduce_max(d,axis=None,keepdims=False,name=None))
print(tf.math.reduce_min(d,axis=None,keepdims=False,name=None))

tf.Tensor(35, shape=(), dtype=int32)
tf.Tensor([ 7 15 13], shape=(3,), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(-1, shape=(), dtype=int32)


In [19]:
s=tf.constant([[1,2,0],
               [3,5,-1],
               [1,5,6],
               [2,3,8]])
tf.math.top_k(s,k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [5],
       [6],
       [8]], dtype=int32)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [1],
       [2],
       [2]], dtype=int32)>)