In [2]:
import tensorflow as tf

In [3]:
tensor_0d=tf.constant(4)
print(tensor_0d)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_1d=tf.constant([2,0,-3])
print(tensor_1d)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [6]:
tensor_oneD=tf.constant([2,0.1,3])
print(tensor_oneD)

tf.Tensor([2.  0.1 3. ], shape=(3,), dtype=float32)


In [ ]:
tensor_2d=tf.constant([[1,2,0],
                       [3,5,-1],
                       [1,5,6],
                       [2,3,8]])
print(tensor_2d)

In [7]:
tensor_3d=tf.constant([[[1,2,0],
                        [3,5,1]],
                        [[10,2,0],
                         [1,0,2]],
                       [[5,8,0],
                        [2,7,0]],
                       [[5,8,0],
                        [2,7,0]],
                       [[2,1,9],
                        [4,-3,32]]])
print(tensor_3d)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5  1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(5, 2, 3), dtype=int32)


In [8]:
tensor_oneD=tf.constant([2,0.2,22],dtype=tf.float32)
casted_tensor=tf.cast(tensor_oneD,dtype=tf.int32)
print(tensor_oneD)
print(casted_tensor)

tf.Tensor([ 2.   0.2 22. ], shape=(3,), dtype=float32)
tf.Tensor([ 2  0 22], shape=(3,), dtype=int32)
